START RequestId: XXXX Version: $LATEST
{"e": XXXX, "m": "aws.lambda.enhanced.invocations", "t": ["region:us-east-1", "account_id:XXXX", "functionname:integration-plugin-dev-http-error_python27_with_plugin", "resource:integration-plugin-dev-http-error_python27_with_plugin", "cold_start:true", "memorysize:1024", "runtime:python2.7", "dd_lambda_layer:datadog-python27_2.XX.0"], "v": 1}
{"e": XXXX, "m": "hello.dog", "t": ["team:serverless", "role:hello", "dd_lambda_layer:datadog-python27_2.XX.0"], "v": 1}
{"e": XXXX, "m": "tests.integration.count", "t": ["test:integration", "role:hello", "dd_lambda_layer:datadog-python27_2.XX.0"], "v": 21}
{"e": XXXX, "m": "aws.lambda.enhanced.errors", "t": ["region:us-east-1", "account_id:XXXX", "functionname:integration-plugin-dev-http-error_python27_with_plugin", "resource:integration-plugin-dev-http-error_python27_with_plugin", "cold_start:true", "memorysize:1024", "runtime:python2.7", "dd_lambda_layer:datadog-python27_2.XX.0"], "v": 1}
{"traces": [[{"resource": "integration-plugin-dev-http-error_python27_with_plugin", "name": "aws.lambda", "service": "aws.lambda", "start": XXXX, "trace_id": "XXXX", "metrics": {"_sampling_priority_v1": 2, "system.pid": XXXX}, "parent_id": "XXXX", "meta": {"runtime-id": "XXXX", "request_id": "XXXX", "cold_start": "true", "function_arn": "arn:aws:lambda:us-east-1:601427279990:function:integration-plugin-dev-http-error_python27_with_plugin", "_dd.origin": "lambda", "_dd.parent_source": "xray", "resource_names": "integration-plugin-dev-http-error_python27_with_plugin", "function_version": "$LATEST"}, "error": 0, "duration": XXXX, "type": "serverless", "span_id": "XXXX"}]]}
Invalid URL 'httpstat.us/400': No schema supplied. Perhaps you meant http://httpstat.us/400?: MissingSchema
Traceback (most recent call last):
  File "/opt/python/lib/python2.7/site-packages/datadog_lambda/wrapper.py", line 106, in __call__
    return self.func(event, context, **kwargs)
  File "/var/task/http_error.py", line 21, in handle
    requests.get("httpstat.us/400")
  File "/opt/python/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/lib/python2.7/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/opt/python/lib/python2.7/site-packages/requests/sessions.py", line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/opt/python/lib/python2.7/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/opt/python/lib/python2.7/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL 'httpstat.us/400': No schema supplied. Perhaps you meant http://httpstat.us/400?
END RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	Init Duration: XXXX ms	
XRAY TraceId: XXXX	SegmentId: XXXX	Sampled: true	
START RequestId: XXXX Version: $LATEST
{"e": XXXX, "m": "aws.lambda.enhanced.invocations", "t": ["region:us-east-1", "account_id:XXXX", "functionname:integration-plugin-dev-http-error_python27_with_plugin", "resource:integration-plugin-dev-http-error_python27_with_plugin", "cold_start:false", "memorysize:1024", "runtime:python2.7", "dd_lambda_layer:datadog-python27_2.XX.0"], "v": 1}
{"e": XXXX, "m": "hello.dog", "t": ["team:serverless", "role:hello", "dd_lambda_layer:datadog-python27_2.XX.0"], "v": 1}
{"e": XXXX, "m": "tests.integration.count", "t": ["test:integration", "role:hello", "dd_lambda_layer:datadog-python27_2.XX.0"], "v": 21}
{"e": XXXX, "m": "aws.lambda.enhanced.errors", "t": ["region:us-east-1", "account_id:XXXX", "functionname:integration-plugin-dev-http-error_python27_with_plugin", "resource:integration-plugin-dev-http-error_python27_with_plugin", "cold_start:false", "memorysize:1024", "runtime:python2.7", "dd_lambda_layer:datadog-python27_2.XX.0"], "v": 1}
{"traces": [[{"resource": "integration-plugin-dev-http-error_python27_with_plugin", "name": "aws.lambda", "service": "aws.lambda", "start": XXXX, "trace_id": "XXXX", "metrics": {"_sampling_priority_v1": 2, "system.pid": XXXX}, "parent_id": "XXXX", "meta": {"runtime-id": "XXXX", "request_id": "XXXX", "cold_start": "false", "function_arn": "arn:aws:lambda:us-east-1:601427279990:function:integration-plugin-dev-http-error_python27_with_plugin", "_dd.origin": "lambda", "_dd.parent_source": "xray", "resource_names": "integration-plugin-dev-http-error_python27_with_plugin", "function_version": "$LATEST"}, "error": 0, "duration": XXXX, "type": "serverless", "span_id": "XXXX"}]]}
Invalid URL 'httpstat.us/400': No schema supplied. Perhaps you meant http://httpstat.us/400?: MissingSchema
Traceback (most recent call last):
  File "/opt/python/lib/python2.7/site-packages/datadog_lambda/wrapper.py", line 106, in __call__
    return self.func(event, context, **kwargs)
  File "/var/task/http_error.py", line 21, in handle
    requests.get("httpstat.us/400")
  File "/opt/python/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/lib/python2.7/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/opt/python/lib/python2.7/site-packages/requests/sessions.py", line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/opt/python/lib/python2.7/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/opt/python/lib/python2.7/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL 'httpstat.us/400': No schema supplied. Perhaps you meant http://httpstat.us/400?
END RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	
XRAY TraceId: XXXX	SegmentId: XXXX	Sampled: true	
START RequestId: XXXX Version: $LATEST
{"e": XXXX, "m": "aws.lambda.enhanced.invocations", "t": ["region:us-east-1", "account_id:XXXX", "functionname:integration-plugin-dev-http-error_python27_with_plugin", "resource:integration-plugin-dev-http-error_python27_with_plugin", "cold_start:false", "memorysize:1024", "runtime:python2.7", "dd_lambda_layer:datadog-python27_2.XX.0"], "v": 1}
{"e": XXXX, "m": "hello.dog", "t": ["team:serverless", "role:hello", "dd_lambda_layer:datadog-python27_2.XX.0"], "v": 1}
{"e": XXXX, "m": "tests.integration.count", "t": ["test:integration", "role:hello", "dd_lambda_layer:datadog-python27_2.XX.0"], "v": 21}
{"e": XXXX, "m": "aws.lambda.enhanced.errors", "t": ["region:us-east-1", "account_id:XXXX", "functionname:integration-plugin-dev-http-error_python27_with_plugin", "resource:integration-plugin-dev-http-error_python27_with_plugin", "cold_start:false", "memorysize:1024", "runtime:python2.7", "dd_lambda_layer:datadog-python27_2.XX.0"], "v": 1}
{"traces": [[{"resource": "integration-plugin-dev-http-error_python27_with_plugin", "name": "aws.lambda", "service": "aws.lambda", "start": XXXX, "trace_id": "XXXX", "metrics": {"_sampling_priority_v1": 2, "system.pid": XXXX}, "parent_id": "XXXX", "meta": {"runtime-id": "XXXX", "request_id": "XXXX", "cold_start": "false", "function_arn": "arn:aws:lambda:us-east-1:601427279990:function:integration-plugin-dev-http-error_python27_with_plugin", "_dd.origin": "lambda", "_dd.parent_source": "xray", "resource_names": "integration-plugin-dev-http-error_python27_with_plugin", "function_version": "$LATEST"}, "error": 0, "duration": XXXX, "type": "serverless", "span_id": "XXXX"}]]}
Invalid URL 'httpstat.us/400': No schema supplied. Perhaps you meant http://httpstat.us/400?: MissingSchema
Traceback (most recent call last):
  File "/opt/python/lib/python2.7/site-packages/datadog_lambda/wrapper.py", line 106, in __call__
    return self.func(event, context, **kwargs)
  File "/var/task/http_error.py", line 21, in handle
    requests.get("httpstat.us/400")
  File "/opt/python/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/lib/python2.7/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/opt/python/lib/python2.7/site-packages/requests/sessions.py", line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/opt/python/lib/python2.7/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/opt/python/lib/python2.7/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL 'httpstat.us/400': No schema supplied. Perhaps you meant http://httpstat.us/400?
END RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	
XRAY TraceId: XXXX	SegmentId: XXXX	Sampled: true	
