START RequestId: XXXX Version: $LATEST
{"e": XXXX, "m": "aws.lambda.enhanced.invocations", "t": ["region:sa-east-1", "account_id:XXXX", "functionname:python-integration-tests-XXXX-sync-metrics_python27", "resource:python-integration-tests-XXXX-sync-metrics_python27", "cold_start:true", "memorysize:1024", "runtime:python2.7", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python27_X.X.X"], "v": 1}
{"e": XXXX, "m": "aws.lambda.enhanced.errors", "t": ["region:sa-east-1", "account_id:XXXX", "functionname:python-integration-tests-XXXX-sync-metrics_python27", "resource:python-integration-tests-XXXX-sync-metrics_python27", "cold_start:true", "memorysize:1024", "runtime:python2.7", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python27_X.X.X"], "v": 1}
HTTP POST https://api.datadoghq.com/api/v1/distribution_points?api_key=XXXX Headers: ["Accept-Encoding:gzip, deflate", "Accept:*/*", "Connection:keep-alive", "Content-Encoding:deflate", "Content-Length:XXXX", "Content-Type:application/json", "User-Agent:datadogpy/0.39.0 (python 2.7.18; os linux; arch x86_64)", "x-datadog-parent-id:XXXX", "x-datadog-sampling-priority:1", "x-datadog-trace-id:XXXX"] Data: {"series": [{"tags": ["team:serverless", "role:hello", "dd_lambda_layer:datadog-python27_X.X.X"], "metric": "hello.dog", "interval": 10, "host": null, "points": [[XXXX, [1.0]]], "device": null, "type": "distribution"}, {"tags": ["test:integration", "role:hello", "dd_lambda_layer:datadog-python27_X.X.X"], "metric": "tests.integration.count", "interval": 10, "host": null, "points": [[XXXX, [21.0]]], "device": null, "type": "distribution"}]}
{"traces": [[{"resource": "python-integration-tests-XXXX-sync-metrics_python27", "name": "aws.lambda", "service": "aws.lambda", "start": XXXX, "trace_id": "XXXX", "metrics": {"_sampling_priority_v1": 1, "system.pid": XXXX, "_dd.agent_psr": 1.0}, "parent_id": "XXXX", "meta": {"http.method": "GET", "runtime-id": "XXXX", "error.type": "exceptions.NameError", "request_id": "XXXX", "function_trigger.event_source": "api-gateway", "cold_start": "true", "datadog_lambda": "X.X.X", "function_arn": "arn:aws:lambda:sa-east-1:601427279990:function:python-integration-tests-XXXX-sync-metrics_python27", "dd_trace": "X.X.X", "_dd.origin": "lambda", "http.status_code": "502", "resource_names": "python-integration-tests-XXXX-sync-metrics_python27", "function_trigger.event_source_arn": "arn:aws:apigateway:sa-east-1::/restapis/wt6mne2s9k/stages/test", "error.msg": "global name 'requests' is not defined", "error.stack": "Traceback (most recent call last):\n  File \"/opt/python/lib/python2.7/site-packages/datadog_lambda/wrapper.py\", line 124, in __call__\n    self.response = self.func(event, context, **kwargs)\n  File \"/var/task/handle.py\", line 27, in handle\n    requests.get(\"https://httpstat.us/200/\")\nNameError: global name 'requests' is not defined\n", "function_version": "$LATEST"}, "error": 1, "duration": XXXX, "type": "serverless", "span_id": "XXXX"}, {"resource": "requests.request", "name": "requests.request", "service": "aws.lambda", "start": XXXX, "trace_id": "XXXX", "metrics": {"_dd.measured": 1}, "parent_id": "XXXX", "meta": {"http.status_code": "202", "http.url": "https://api.datadoghq.com/api/v1/distribution_points", "_dd.origin": "lambda", "http.method": "POST"}, "error": 0, "duration": XXXX, "type": "http", "span_id": "XXXX"}]]}
global name 'requests' is not defined: NameError
Traceback (most recent call last):
  File "/opt/python/lib/python2.7/site-packages/datadog_lambda/wrapper.py", line 124, in __call__
    self.response = self.func(event, context, **kwargs)
  File "/var/task/handle.py", line 27, in handle
    requests.get("https://httpstat.us/200/")
NameError: global name 'requests' is not defined
END RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	Init Duration: XXXX ms	
START RequestId: XXXX Version: $LATEST
{"e": XXXX, "m": "aws.lambda.enhanced.invocations", "t": ["region:sa-east-1", "account_id:XXXX", "functionname:python-integration-tests-XXXX-sync-metrics_python27", "resource:python-integration-tests-XXXX-sync-metrics_python27", "cold_start:false", "memorysize:1024", "runtime:python2.7", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python27_X.X.X"], "v": 1}
{"e": XXXX, "m": "aws.lambda.enhanced.errors", "t": ["region:sa-east-1", "account_id:XXXX", "functionname:python-integration-tests-XXXX-sync-metrics_python27", "resource:python-integration-tests-XXXX-sync-metrics_python27", "cold_start:false", "memorysize:1024", "runtime:python2.7", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python27_X.X.X"], "v": 1}
HTTP POST https://api.datadoghq.com/api/v1/distribution_points?api_key=XXXX Headers: ["Accept-Encoding:gzip, deflate", "Accept:*/*", "Connection:keep-alive", "Content-Encoding:deflate", "Content-Length:XXXX", "Content-Type:application/json", "User-Agent:datadogpy/0.39.0 (python 2.7.18; os linux; arch x86_64)", "x-datadog-parent-id:XXXX", "x-datadog-sampling-priority:1", "x-datadog-trace-id:XXXX"] Data: {"series": [{"tags": ["team:serverless", "role:hello", "dd_lambda_layer:datadog-python27_X.X.X"], "metric": "hello.dog", "interval": 10, "host": null, "points": [[XXXX, [1.0]]], "device": null, "type": "distribution"}, {"tags": ["test:integration", "role:hello", "dd_lambda_layer:datadog-python27_X.X.X"], "metric": "tests.integration.count", "interval": 10, "host": null, "points": [[XXXX, [21.0]]], "device": null, "type": "distribution"}]}
{"traces": [[{"resource": "python-integration-tests-XXXX-sync-metrics_python27", "name": "aws.lambda", "service": "aws.lambda", "start": XXXX, "trace_id": "XXXX", "metrics": {"_sampling_priority_v1": 1, "system.pid": XXXX, "_dd.agent_psr": 1.0}, "parent_id": "XXXX", "meta": {"runtime-id": "XXXX", "error.type": "exceptions.NameError", "request_id": "XXXX", "function_trigger.event_source": "sns", "cold_start": "false", "datadog_lambda": "X.X.X", "function_arn": "arn:aws:lambda:sa-east-1:601427279990:function:python-integration-tests-XXXX-sync-metrics_python27", "dd_trace": "X.X.X", "_dd.origin": "lambda", "resource_names": "python-integration-tests-XXXX-sync-metrics_python27", "function_trigger.event_source_arn": "arn:aws:sns:us-east-2:123456789012:sns-lambda", "error.msg": "global name 'requests' is not defined", "error.stack": "Traceback (most recent call last):\n  File \"/opt/python/lib/python2.7/site-packages/datadog_lambda/wrapper.py\", line 124, in __call__\n    self.response = self.func(event, context, **kwargs)\n  File \"/var/task/handle.py\", line 27, in handle\n    requests.get(\"https://httpstat.us/200/\")\nNameError: global name 'requests' is not defined\n", "function_version": "$LATEST"}, "error": 1, "duration": XXXX, "type": "serverless", "span_id": "XXXX"}, {"resource": "requests.request", "name": "requests.request", "service": "aws.lambda", "start": XXXX, "trace_id": "XXXX", "metrics": {"_dd.measured": 1}, "parent_id": "XXXX", "meta": {"http.status_code": "202", "http.url": "https://api.datadoghq.com/api/v1/distribution_points", "_dd.origin": "lambda", "http.method": "POST"}, "error": 0, "duration": XXXX, "type": "http", "span_id": "XXXX"}]]}
global name 'requests' is not defined: NameError
Traceback (most recent call last):
  File "/opt/python/lib/python2.7/site-packages/datadog_lambda/wrapper.py", line 124, in __call__
    self.response = self.func(event, context, **kwargs)
  File "/var/task/handle.py", line 27, in handle
    requests.get("https://httpstat.us/200/")
NameError: global name 'requests' is not defined
END RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	
START RequestId: XXXX Version: $LATEST
{"e": XXXX, "m": "aws.lambda.enhanced.invocations", "t": ["region:sa-east-1", "account_id:XXXX", "functionname:python-integration-tests-XXXX-sync-metrics_python27", "resource:python-integration-tests-XXXX-sync-metrics_python27", "cold_start:false", "memorysize:1024", "runtime:python2.7", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python27_X.X.X"], "v": 1}
{"e": XXXX, "m": "aws.lambda.enhanced.errors", "t": ["region:sa-east-1", "account_id:XXXX", "functionname:python-integration-tests-XXXX-sync-metrics_python27", "resource:python-integration-tests-XXXX-sync-metrics_python27", "cold_start:false", "memorysize:1024", "runtime:python2.7", "datadog_lambda:vXX", "dd_lambda_layer:datadog-python27_X.X.X"], "v": 1}
HTTP POST https://api.datadoghq.com/api/v1/distribution_points?api_key=XXXX Headers: ["Accept-Encoding:gzip, deflate", "Accept:*/*", "Connection:keep-alive", "Content-Encoding:deflate", "Content-Length:XXXX", "Content-Type:application/json", "User-Agent:datadogpy/0.39.0 (python 2.7.18; os linux; arch x86_64)", "x-datadog-parent-id:XXXX", "x-datadog-sampling-priority:1", "x-datadog-trace-id:XXXX"] Data: {"series": [{"tags": ["team:serverless", "role:hello", "dd_lambda_layer:datadog-python27_X.X.X"], "metric": "hello.dog", "interval": 10, "host": null, "points": [[XXXX, [1.0]]], "device": null, "type": "distribution"}, {"tags": ["test:integration", "role:hello", "dd_lambda_layer:datadog-python27_X.X.X"], "metric": "tests.integration.count", "interval": 10, "host": null, "points": [[XXXX, [21.0]]], "device": null, "type": "distribution"}]}
{"traces": [[{"resource": "python-integration-tests-XXXX-sync-metrics_python27", "name": "aws.lambda", "service": "aws.lambda", "start": XXXX, "trace_id": "XXXX", "metrics": {"_sampling_priority_v1": 1, "system.pid": XXXX}, "parent_id": "XXXX", "meta": {"runtime-id": "XXXX", "error.type": "exceptions.NameError", "request_id": "XXXX", "function_trigger.event_source": "sqs", "cold_start": "false", "datadog_lambda": "X.X.X", "function_arn": "arn:aws:lambda:sa-east-1:601427279990:function:python-integration-tests-XXXX-sync-metrics_python27", "dd_trace": "X.X.X", "_dd.origin": "lambda", "resource_names": "python-integration-tests-XXXX-sync-metrics_python27", "function_trigger.event_source_arn": "arn:aws:sqs:us-east-2:123456789012:my-queue", "error.msg": "global name 'requests' is not defined", "error.stack": "Traceback (most recent call last):\n  File \"/opt/python/lib/python2.7/site-packages/datadog_lambda/wrapper.py\", line 124, in __call__\n    self.response = self.func(event, context, **kwargs)\n  File \"/var/task/handle.py\", line 27, in handle\n    requests.get(\"https://httpstat.us/200/\")\nNameError: global name 'requests' is not defined\n", "function_version": "$LATEST"}, "error": 1, "duration": XXXX, "type": "serverless", "span_id": "XXXX"}, {"resource": "requests.request", "name": "requests.request", "service": "aws.lambda", "start": XXXX, "trace_id": "XXXX", "metrics": {"_dd.measured": 1}, "parent_id": "XXXX", "meta": {"http.status_code": "202", "http.url": "https://api.datadoghq.com/api/v1/distribution_points", "_dd.origin": "lambda", "http.method": "POST"}, "error": 0, "duration": XXXX, "type": "http", "span_id": "XXXX"}]]}
global name 'requests' is not defined: NameError
Traceback (most recent call last):
  File "/opt/python/lib/python2.7/site-packages/datadog_lambda/wrapper.py", line 124, in __call__
    self.response = self.func(event, context, **kwargs)
  File "/var/task/handle.py", line 27, in handle
    requests.get("https://httpstat.us/200/")
NameError: global name 'requests' is not defined
END RequestId: XXXX
REPORT RequestId: XXXX	Duration: XXXX ms	Billed Duration: XXXX ms	Memory Size: 1024 MB	Max Memory Used: XXXX MB	
